# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Infisical MCP Server
# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY . ./
RUN npm run build

# Stage 2: Production image
FROM node:lts-alpine
WORKDIR /app

# Install production dependencies
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts

# Copy built artifacts
COPY --from=builder /app/dist ./dist

# Set environment
ENV NODE_ENV=production

# Entry point for MCP server
ENTRYPOINT ["node","dist/index.js"]
